name: NekoyaLevelBorder
description: $description
version: '${version}'

main: at.darkichen.levelBorder.LevelBorder
api-version: '26.1.2'
load: POSTWORLD

authors: [ Darkichen ]

commands:
  levelborder:
    description: LevelBorder main command